### ISSUE TITLE
Travis CI is called twice on new pull requests

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#133]
As the subject says:

![image](https://user-images.githubusercontent.com/3105685/66254780-92b77100-e77b-11e9-8b69-7bfbede55dcc.png)

**Comment by ottok** [comment]
Yes, this happens if the user has never pushed that commit to Github/Travis before. It should point to the same build however since the commit ID is the same. I'll have a look next time this happens.

**Comment by ottok** [comment]
Indeed, the links point to separate builds, eg:
* https://travis-ci.org/rdiff-backup/rdiff-backup/builds/594019267?utm_source=github_status&utm_medium=notification
* https://travis-ci.org/rdiff-backup/rdiff-backup/builds/594019261?utm_source=github_status&utm_medium=notification

But they also represent two different commits:
* https://github.com/rdiff-backup/rdiff-backup/commit/ee7f8656966c759e2edc00099b43e31de7b03b7b
* https://github.com/rdiff-backup/rdiff-backup/commit/40ef3afe8b28ff62f37da9c964e062da4a88d005

So this is by design correct?

**Comment by ericzolf** [comment]
Could it be due to `git push --force` overwriting the old commit? I can't find ee7f865 in my Git repo, GitHub itself shows the link as "Merge 40ef3af into 32b098f", but 40ef3af still exists in my Git repo though not in my log (but I have pushed since then a new commit version, so it might just be a dangling commit).

The result is definitely not right, the tests should only run once, but how to fix, no clue as I have no clue of Travis CI.

**Comment by ericzolf** [comment]
OK, it was due to https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests so I shut off the build on push branches.
