### ISSUE TITLE
bash completion: outdated path

### ISSUE THREAD

**Issue by MestreLion** [rdiff-backup/rdiff-backup#169]
Since the bash completion script was recently moved from Debian to upstream repository I'll fill the bug report here:

Currently the script is installed at `/etc/bash_completion.d/rdiff-backup`, but from at least 2012 bash completions default vendor dir is `/usr/share/bash-completion/completions`. This can be checked with `pkg-config --variable=completionsdir bash-completion`. Currently `/etc/bash_completion` and files at `/etc/bash_completion.d` are mere shims/stubs that source from the correct path.

Sources:
https://github.com/scop/bash-completion
https://salsa.debian.org/debian/bash-completion

if needed I can shortly provide a patch to fix this.

**Comment by frankcrawford** [comment]
While Debian has moved it, do you know if other dists have also moved it?  Also, will it roll through to older versions of Debian, or will we need to do some dist/version checking before installation?

**Comment by ericzolf** [comment]
I agree with Frank, the issue is that we're "upstream" not packager, and we need to take the most generic approach, leaving it to the specialized packagers to do the fine tuning for their distro.

**Comment by ericzolf** [comment]
Just checked the git log of bash-completion and it recommends the new path since 2011 :older_man: 
So I think we can safely use the new path (ah, I oversaw the hint to 2012 in your description @MestreLion sorry!).

A patch would be cool. You need to rename the `rdiff-backup.bash` to `rdiff-backup` (the exact name of the command), please move it then to `tools/bash_completions/rdiff-backup` and adapt `setup.py` accordingly.

Thanks in advance!
