### ISSUE TITLE
What files in tools/misc should be distributed?

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#187]
Looking at the files in tools/misc, some of them, such as `compress-rdiff-backup-increments` look like they would be good to include in a distribution, but others, like `make-many-data-files.py` are more for just development.

Which are which, and can we get setup.py to move them into somewhere useful to add distributions?

**Comment by ericzolf** [comment]
My first and direct answer would be, none for now and whatever we decide, none in the upcoming release:

1, because it's too late for the release (see below why I think so)
2. because it requires some work to make it safely, as most are either useless or useful but dangerous
3. if a user needs one, he can ask for help and our answer might be, grab the script from misc, but we keep the control

Now, if we want to deliver some of those scripts, we should follow this approach (subject to discussion):

1. answer positively the question if it makes sense to have as separate script, or if it should rather be a feature of the main script.
2. move the script to `src/` and rename it to `rdiff-backup-something`
3. create a man-page (or a markdown page and convert to troff)
4. add test cases to the test suite (something we should do for `rdiff-backup-statistics` BTW)

Does it make sense?

**Comment by ikus060** [comment]
I'm aligned with all your recommendation Eric.
We should not redistribute those files, and if we want to share them, let it make part of rdiff-backup in a similar way to rdiff-backup-statistics (with proper testcases, under /src/, documented, etc.)

**Comment by frankcrawford** [comment]
I don't entirely agree, in that I've sometimes found having such tools around in the distribution helps in understanding the more unusual issue particularly when support is slow or even non-existent.

However, I'm also not too worried about it for the present and am fine to leave it for a later time.

**Comment by ericzolf** [comment]
I'd like to come back on this issue now that we're coming nearer to the next release. I've gone quickly through the scripts and they're (IMHO) either made irrelevant by new features (e.g. regress or deldiffs), or they're more files meant to help development. So I wouldn't include them in your RPM, but it remains of course your choice. Only important to me is that:

1. it's clear that nothing under misc is supported
2. we can close this issue :smile:

**Comment by ikus060** [comment]
> it's clear that nothing under misc is supported

Agreed.

**Comment by ericzolf** [comment]
OK, closing the issue, I don't think there is more to discuss. Thanks for your attention.
