### ISSUE TITLE
Hard linked files incorrectly stored and cause error messages

### ISSUE THREAD

**Issue by rknichols** [rdiff-backup/rdiff-backup#237]
Running a test that includes the heavily hard linked files in /var/lib/yum/yumdb, each link yields an error message, "Updated mirror temp file ... does not match source", and all of the files in the archive have just one link. Only 2558 of 14291 files were stored. Testing done with rdiff_backup-1.4.0b1.dev4+gd9977cf-cp36-cp36m-linux_x86_64.

**Comment by ericzolf** [comment]
In regard to hard links, I know only one issue #78 which isn't though your issue. The message you pin point happens when a process is changing the source files while the backup runs, we also have an issue for this one but it is an enhancement request IMHO "Support backup of files changing during backup time #8".

Could you please make sure that dnf/yum/etc doesn't run in the background and retry the backup action (with -v9 even better)? I know that you are doing it with CentOS 8 64 bit and Python 3.6.8 but also the exact command line as you typed it would be good to have. The log files `rdiff-backup-data/*.log` in the backup repo would also be of great help.

**Comment by ericzolf** [comment]
Sorry, the correct pattern for log files is `rdiff-backup-data/*[._]log*` (error_log.DATETIME would have been missed). BTW, I can't reproduce your issue, at least not on Fedora.

**Comment by rknichols** [comment]
The files are definitely not being changed. This is a **copy** of the /var filesystem of a CentOS 6 installation, and is not an active filesystem. The logs would have been quite large (>3.5MB). I've run another test covering just /var/home, which holds just a few files with multiple links. The command:

rdiff-backup -b --preserve-numerical-ids --print-statistics /mnt/c6var/var/home /mnt/c6varbkup/home

When I try to attach the log files, I just get a message in red,"Something went really wrong, and we can't process that file." Here is the unzipped content of the error_log file. The backup.log file is identical, but with the session statistics appended.

b"UpdateError rnichols/bin/lba2chs Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6841' does not match source"
b"UpdateError rnichols/bin/nsync-from-3a Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6846' does not match source"
b"UpdateError rnichols/bin/nsync-from-3f Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6847' does not match source"
b"UpdateError rnichols/bin/nsync-from-3g Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6848' does not match source"
b"UpdateError rnichols/bin/nsync-from-3p Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6849' does not match source"
b"UpdateError rnichols/bin/nsync-from-3pw Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6850' does not match source"
b"UpdateError rnichols/bin/nsync-from-home Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6851' does not match source"
b"UpdateError rnichols/bin/sync-from-3f Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6880' does not match source"
b"UpdateError rnichols/bin/sync-from-3p Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6881' does not match source"
b"UpdateError rnichols/bin/sync-from-3pw Updated mirror temp file b'/mnt/c6varbkup/home/rnichols/bin/rdiff-backup.tmp.6882' does not match source"

**Comment by rknichols** [comment]
It's an issue with security contexts. Because my external backup drive is shared among systems that have either incompatible SElinux contexts or no SElinux at all, that drive is mounted with an overriding context option "-o context=system_u:object_r:default_t:s0". Apparently rdiff-backup is complaining that the security context of the rdiff-backup.tmp.xxxx file does not match the source. It does this only for the second or later links to a hard linked file. Since there is no requirement that the archive filesystem support SElinux at all, rdiff-backup should not be checking this. rdiff-backup 1.2 does not exhibit this problem.

**Comment by ericzolf** [comment]
Well, it's overall extended attributes which are checked and it isn't specific to SELinux. But the check validates that EAs are supported or not, it isn't foreseen that they are partially supported respectively that they are modified out of thin air (so to say).

IMHO you can get around the issue by using the `--no-eas` option; can you check? rdiff-backup 1.2 might not show the behaviour because you haven't installed xattr for Python 2?

Finding a solution is also non-trivial: how do you make the difference between a valid and an invalid change? We would need probably a new flag stating "save EAs but don't check them". This would be an enhancement request and not a bug, even less a regression. But let's wait the result of your tests before we decide.

**Comment by rknichols** [comment]
Not saving the extended attributes is totally unacceptable. My rdiff-backup 1.2 is definitely saving SElinux extended attributes in the rdiff-backup-data metadata files. The forced context of course prevents saving them in the mirror. Version 1.2 is totally happy with this.

**Comment by frankcrawford** [comment]
FYI, I've now built both python3-pyxattr and py3libacl in COPR, which you can install by downloading the relevant repo files from https://copr.fedorainfracloud.org/coprs/frankcrawford/
Note that I haven't tested them too much so far.

**Comment by zjw** [comment]
Pull request #241 has been created to address this issue.
