### ISSUE TITLE
Incorrect hard linking in mirror

### ISSUE THREAD

**Issue by rknichols** [rdiff-backup/rdiff-backup#272]
#240 appears to fix the hard link issues I've seen in rdiff-backup 1.9.0b1.dev8, but there is still a sequence that leaves files incorrectly linked in the mirror, though the mirror_metadata file has the linking correct. Starting with a backup including file with 4 links, remove the first link and add a new one. Backing that up results in a mirror with 2 files with 2 links each.
```
[localhost tmp]# ls -li rbtest
total 0
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file1
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file2
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file3
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file4
[localhost tmp]# rdiff-backup rbtest rbtest.bk
[localhost tmp]# ls -li rbtest.bk
total 4
664 -rw-r--r--. 4 root root    0 Feb 15 21:56 file1
664 -rw-r--r--. 4 root root    0 Feb 15 21:56 file2
664 -rw-r--r--. 4 root root    0 Feb 15 21:56 file3
664 -rw-r--r--. 4 root root    0 Feb 15 21:56 file4
628 drwx------. 3 root root 4096 Feb 15 21:57 rdiff-backup-data
[localhost tmp]# rm rbtest/file1
[localhost tmp]# ln rbtest/file4 rbtest/file5
[localhost tmp]# ls -li rbtest
total 0
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file2
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file3
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file4
603 -rw-r--r--. 4 root root 0 Feb 15 21:56 file5
[localhost tmp]# rdiff-backup rbtest rbtest.bk
[localhost tmp]# ls -li rbtest.bk
total 4
696 -rw-r--r--. 2 root root    0 Feb 15 21:56 file2
664 -rw-r--r--. 2 root root    0 Feb 15 21:56 file3
664 -rw-r--r--. 2 root root    0 Feb 15 21:56 file4
696 -rw-r--r--. 2 root root    0 Feb 15 21:56 file5
628 drwx------. 3 root root 4096 Feb 15 21:58 rdiff-backup-data

```
The mirror_metadata file shows all 4 names with the same inode and 4 links.

**Comment by ericzolf** [comment]
It doesn't sound neither like a critical bug nor like a regression towards 1.2/1.3 so we'll handle it in the next version.

**Comment by rknichols** [comment]
Agreed. While I would dearly love to get rid of the absurdly complex hard link audit I run after every backup, I've lived with it for quite a few years now.

**Comment by ericzolf** [comment]
Still looking into it but it seems more difficult than I initially thought because rdiff-backup is doing the right thing according to the current logic:
1. the first file is changed/removed
2. the 2nd file is also modified according to the metadata because the checksum needs to be attached to it now, hence rdiff-backup creates a delta (and hence creates a new file with a new inode in the repo)
3. the middle (3rd and 4th) files haven't changed so nothing is modified and they keep the old inode
4. and the last file is also changed/added so it takes the new inode...

Each step individually is correct, and even a restore works correctly, but the result in the repo isn't completely consistent.
if I also change the content or the mdate of the underlying file (through the new file) then everything is back to normal because the "middle" files have also been modified. So I need either to:

1. introduce a new state "metadata modified but not content"
2. or consider all files with the same inode modified if one is modified.

Approach 1 would be the clean one but would be equivalent to always checksum content (big performance impact!) and would probably imply a repository format change (there would be metadata files without corresponding increments).
Approach 2 isn't as nice or generic but it would probably be with less impact overall, and would have the expected result.

**Comment by rknichols** [comment]
rdiff-backup (version 1.2, at least) is totally happy with metadata changes that lack a corresponding increment. I have an audit that I run daily to remove unneeded zero-diff increment files that result primarily from hard link changes. The first time I ran it on a drive containing several years of backups, it deleted over 4,000,000 files. Here are the comment lines from the top of that audit:

#!/bin/bash
# Clean out the "zero-diff" increment files and adjust the file_statistics
# file to match.
#
# Look in a file_statistics file for files that have a change flagged
# and a non-zero increment size.  For each of those files, examine the
# changes in the mirror_metadata file.  If there are no changes except
# possibly to NumHardLinks, Inode, and DeviceLoc, then the change flag
# and change size can be zeroed in file_statistics and the "zero-diff"
# file can be removed from the increments.
#
# The file_statistics file is never actually read by rdiff-backup, so
# the cleanup in that file is just for the rdiff-backup-statistics
# report..

**Comment by ericzolf** [comment]
That's an interesting fact, thanks. Would you mind sharing your script, e.g. placed as PR in `tools/misc` ?

**Comment by rknichols** [comment]
OK. I think I have done that. The file submitted is deldiffs.sh in tools/misc (hopefully).
