### ISSUE TITLE
Replace rdiff-backup logo

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#286]
Thanks to @ericzolf rdiff-backup has an icon, but we must admit it's not very professional. I'm working with a designer and I've asked her to create a new logo for rdiff-backup. Something more professional!

Here the results so far, she's waiting for our feedback. @frankcrawford @ottok 

* This version is nice to put in a banner on the website and github README. I may ask for a squared version of the logo if you think it's useful.
*For the colour scheme, she used the blue from the current logo. But the web site if using red. Which one you prefer ? Red or blue ?

![Screenshot from 2020-02-25 11-23-20](https://user-images.githubusercontent.com/921251/75273427-d5cbbc80-57ce-11ea-954f-425214ed057c.png)

**Comment by ericzolf** [comment]
It took me 15min or so to create the logo, and just to have any one, so no bad blood.

* I like the way RdiffBACKUP is written
* The logo is definitely more compelling than the old one, but is also a lot more complex, IMHO slightly too complex for a logo. I think, it would already be better to have a single arrow _between_ the two stacks of disks, with the green part on the right hand side of the left stack.
* the arrow should IMHO be more special / specific so that it can be a central element of a simpler logo (next bullet)
* we need a much simpler squared logo, which can also be used as icon on desktops (think 32x32 dots), perhaps only one stack of disks and _the_ arrow.
* we need the source code in our GitHub repo, as SVG or similar.
* I like the blue & green combination (and black), red & green would be quite aggressive IMHO.

**Comment by ikus060** [comment]
> but is also a lot more complex, IMHO slightly too complex for a logo.
Agree with you, I will try to clarify this point with here.

> we need a much simpler squared logo
Yes, that's what I mention at the beginning, but nothing prevent us to have multiple variation of the "logo" for icon and banner.

> we need the source code in our GitHub repo, as SVG or similar.
Yes, will have the SVG and it will be release as part of the project and under GPL license.

> I like the blue & green combination (and black),
Then will stick with the blue.
But will need to change the CSS of the website...

**Comment by ericzolf** [comment]
> Yes, that's what I mention at the beginning, but nothing prevent us to have multiple variation of the "logo" for icon and banner.

That's also what I meant, so we're fine.
