### ISSUE TITLE
Authors of PRs are not logged in commit messages when merging

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#289]
I just noticed that when squashing, and probably also merging, it's the merger who gets documented as author (and GitHub itself as committer), and not the initial author of the PR, which is an issue, especially for `./tools/get_changelog_since.sh`. I have no idea how to resolve this for now.

**Comment by ericzolf** [comment]
Seems related to https://github.com/isaacs/github/issues/1368 - using `on-behalf-of` in the squash commit message might a solution/workaround.

**Comment by ottok** [comment]
I have not come across this phenomenon ever. Probably because I never use "squash and merge" on Github, only real merges (with merge commit) or "rebase and merge" without merge commits. Maybe just recommend not to do squashing? I see other problems with squashing as well as I've pointed out before.

**Comment by ericzolf** [comment]
Well, it also has advantages: https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/

**Comment by ericzolf** [comment]
And we didn't see the issue before because it is very new and will be soon fixed, see last comment of https://github.com/isaacs/github/issues/1303

**Comment by ikus060** [comment]
For the time being, I don't mind merging my own commit or something like this.

**Comment by ericzolf** [comment]
Already fixed!

**Comment by ottok** [comment]
> Well, it also has advantages: https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/

This article presents squashing as a solution to 1) messy history after merges and 2) badly written commit messages.

Squashing is not the solution. The best practice is for developers to run `git rebase -i` to ensure their changes start from the latest upstream git master and that they make their commits properly atomic and write good titles and bodies to them.

Squashing will always make all pull requests into one single commit, and if the PR was correctly structured and each commit was independent and atomic, all that info is lost on squashing. Also, squashing places the burden of describing the change on the person doing the squash. As we see in this issue, squashing on Github also looses the information on the merge approver. There is just Author in the one commit, no Committer and no merge commit.

At the end the article authors admit that people have started to criticize them and suggest using git rebase (as the original text lacked rebases completely). Their reply on avoiding `git push --force` is misguided. There is no need to permanently save intermediate development time stuff. Force pushing development branches is just fine. No information is lost either, people can look at the diff between the different versions as long as there the commit ids visible.

I contribute to tens of open source projects and they all use git rebasing just as it is meant to do. Using a git squash on merge is very rare, usually only happens if the original author of the PR was very sloppy.
