### ISSUE TITLE
[BUG] Backport to trusty not working.

### ISSUE THREAD

**Issue by pnunn** [rdiff-backup/rdiff-backup#330]
## Bug summary

I've added the backport ppa to a trusty server but when I try and install it I'm getting 

Failed to fetch http://ppa.launch.net/....  404 Not Found [19: 91.189.95.83 80]

Any idea what I'm doing wrong?

**Comment by ottok** [comment]
Can you please elaborate, what backport did you add? To my knowledge there is no backport to Trusty and Ubuntu 14.04 "Trusty" is out of support anyway, you should not be using it anymore.

**Comment by pnunn** [comment]
Ahh.. that may be the problem then.. I just added the ppa
`ppa:rdiff-backup/rdiff-backup-backports`

Is there any way to get 2.0 on this old system? I have broken my backups by upgrading the backup host to 2.0 without realising it would break the older systems (my stuff up entirely). 

In these crazy times we are living in I don't want to risk upgrading this system remotely and I can't visit site currently for obvious reasons.

**Comment by ikus060** [comment]
The best os to follow the instructions for the "other" platform from the
readme.

You will install rdiff-backup from pypi.

**Comment by ottok** [comment]
Backporting to Xenial or Trusty would require building setuptools-scm for them, which in turn would also require building pytest for those distros, and in order to build a pytest backport from Bionic one would also need to make a modified verision of pytest or backport it's build dependencies debhelper (>= 11), pypy-attr (>= 17.2.0), pypy-funcsigs, pypy-hypothesis (>= 3.44.1-2~), pypy-pluggy (>= 0.5), pypy-py (>= 1.5.0), pypy-setuptools-scm, python-attr (>= 17.2.0), python-pluggy (>= 0.5), python-py (>= 1.5.0), python3-attr (>= 17.2.0), python3-pluggy (>= 0.5), python3-py (>= 1.5.0).

Build logs of my attempts can be seen at https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-backports/+builds?build_text=&build_state=all

Maybe if we do a version that builds without python-setuptools-scm the backport could be a bit more feasible. However Trusty is already out of support since 1 year, and Xenial will be next year, so I don't think there is much point investing our precious time into this unless there is somebody who considers this very very critical and wants to sponsor such work.

I think a better approach is to use the https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-legacy PPA and install the legacy 1.3.3 on your newer systems, and run a fully 1.3.3 environment until those old Trusty machines have been upgraded and you are ready to upgrade ro rdiff-backup 2.0 everywhere.

**Comment by pnunn** [comment]
Thanks guys,  I just followed the "other platform" instructions as suggested by @ikus060  and after a bit of sim linking around the place it is now running. I'll get this upgraded as soon as I can after this mess is over.

I was thinking about down grading the receiving server, but this seems to be working OK now.  Ninjahelper just completed the backup so all good.. thanks again, and thanks for the work.

**Comment by ericzolf** [comment]
User happy, issue closed :+1:
