### ISSUE TITLE
No longer parsing exclude-globbing-filelist

### ISSUE THREAD

**Issue by sccjono** [rdiff-backup/rdiff-backup#357]
## Directories and files are being included on Windows.

Today I replaced v1.2.8 with v2.0.0 and I discover that the following command line, which has always worked, is now trying to include directories listed in exclude-list.

`rdiff-backup -v9 --no-acls --exclude-globbing-filelist exclude-list "c:/Users/Jon Hunt/" "g:/Backup"`

The content of the file are as follows.

`c:/Users/Jon Hunt/NTUSER.DAT
c:/Users/Jon Hunt/.*
c:/Users/Jon Hunt/Dropbox
c:/Users/Jon Hunt/AppData
c:/Users/Jon Hunt/MicrosoftEdgeBackups`

However, straight away the program attempts to backup the "AppData" directory.

## Version, Python, Operating System
Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
2020-05-12 14:37:00.990779 +0100  <CLIENT-11916>  Using rdiff-backup version 2.0.0
2020-05-12 14:37:00.991774 +0100  <CLIENT-11916>        with cpython C:\WINDOWS\rdiff-backup.exe version 3.7.5
2020-05-12 14:37:00.993768 +0100  <CLIENT-11916>        on Windows-10-10.0.18362, fs encoding utf-8
2020-05-12 14:37:00.993768 +0100  <CLIENT-11916>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
```

**Comment by ericzolf** [comment]
It seems indeed that there is an issue with this. I'll have to look deeper into it.

**Comment by ericzolf** [comment]
I didn't yet find the time to ultimately verify but it seems that the issue is due to DOS line endings `\r\n` vs. UNIX/Linux line endings `\n`. It should be relatively easy to fix but I want also to clean up the code and consider Mac endings (if there is still such a thing).

Anyway, in the meantime, as an unverified workaround, you should be able to write the selection file in UNIX format and it should work (using [Vim](https://www.vim.org/download.php#pc), open the selection file and type `:set ff=unix` and `:w`). Let me know if it works for you, then I don't need to test myself :smirk: .

**Comment by sccjono** [comment]
Yes I can confirm that after checking your workaround works perfectly. Thank you.
