### ISSUE TITLE
[BUG] Cannot back up remote files with Turkish characters in the filename

### ISSUE THREAD

**Issue by oktayaa** [rdiff-backup/rdiff-backup#462]
### LOCALHOST:

Debian Buster
rdiff-backup version     2.0.5  (Installed locally in user's bin)

$ python3 --version
Python 3.7.3

$ env | grep -e LC -e LANG
LANG=en_US.UTF-8
LC_ALL=en_US

### REMOTEHOST:

Centos     7.8
rdiff-backup version     2.0.5

$ python3 --version
Python 3.6.8

$ env | grep -e LC -e LANG
LANG=en_US.UTF-8

### Command from LOCALHOST:

`LANG=en_US.UTF-8 rdiff-backup --print-statistics --remote-schema 'ssh -C %s "sudo /bin/rdiff-backup --server --restrict-read-only /"' erp::/home/ias/604server /tmp/temp`

(%s is defined in the ssh config)

### Error Message sample:

`Warning: unable to read default ACL from /storage/rdiff-backup/[ REDACTED ]/604server/D:/\u0130stemciler: [Errno 2] No such file or directory`

where \u0130 is the Turkish capital i character " İ ".

**Comment by oktayaa** [comment]
I checked the actual remote files again. Apparently it wasn't just an İ, it is preceeded by a directory name with a  semicolon in it. i.e D:/İstemciler .

It seems to be some sort of Windows stuff on the Linux disk which our ERP consultants must have copied over. There's nothing useful in it to back up. This is a very edge case but perhaps something that is legal (creating directory names with semicolons in them) should be handled. I am closing the bug.

**Comment by oktayaa** [comment]
Actually reopening. I encountered other files with no interesting characters in it except for being Turkish. (The ü char for instance). Though I also found some filenames containing single quote characters.

**Comment by ericzolf** [comment]
I don't have right now the time to test it myself, but the `LC_ALL=en_US` doesn't sound right to me, it should read like LANG, with the same UTF-8 encoding included.

Everything legit to the file system should be legit to rdiff-backup, potential bugs not considered of course. The warning you sent us is actually just what it says, a warning, meaning the backup should still work, but the ACLs might get lost. Can you confirm that it is like I described, i.e. the files are backed-up and it's just a warning about the ACLs? Checking the ACLs can be a bit tricky, as there might be no ACLs attached to the file (the warning is that it couldn't even check this, here we're relying on the underlying library). You can try to check this with the following one-liner (`/var/tmp` being the file to check, encoded because we use bytes in rdiff-backup):

```bash
python -c 'import posix1e, os; print(posix1e.ACL(file=os.fsencode("/var/tmp")))'
```

Adding `-v9` for more verbosity and providing  a longer log might help us better pin point the issue.

**Comment by oktayaa** [comment]
I assumed they were not being backed because of the end of the error message:  "[Errno 2] No such file or directory" but I will check and also try setting the LANG to the same thing. Is it a problem that LANG is not set at all on the remote side?

**Comment by oktayaa** [comment]
At any rate, setting LANG to en_US.UTF8 fixed this. Thanks.
