### ISSUE TITLE
Fatal Error: Target file system isn't deemed reliable enough for a backup.

### ISSUE THREAD

**Issue by MHBraun** [rdiff-backup/rdiff-backup#521]
Attempting to backup `/home/me` to ` /media/me/backup/rdiff` with
`rdiff-backup --include-symbolic-links --exclude-other-filesystems /home/me /media/me/backup/rdiff`
is resulting in the error
Fatal Error: We're sorry but the target file system at '/media/backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.0' isn't deemed reliable enough for a backup. It takes too long or doesn't register case insensitive deletion of files.
rdiff-backup does interrupt the backup after creating .../rdiff-backup-data/rdiff-backup.tmp.0

/media/me/backup/ is a samba shared cifs drive on an underlaying zfs filesystem running on Lubuntu 18.04 LTS.
Are samba cifs shares or the ZFS file system not supported?

**Comment by ericzolf** [comment]
We don't support or not support specific file systems. We just do tests and refuse to work if they fail. Basically the equivalent of `touch TEST && rm test && [[ -f TEST ]] && echo FAILED` on a case insensitive file system like CIFS. I guess that the issue is putting a case insensitive file system on top of a case sensitive one, plus some network latency. You are probably better served to use NFS, or use the client/server function of rdiff-backup. Please close the issue unless you have further questions.

**Comment by MHBraun** [comment]
Thank you for your quick answer and pushing me into the right direction.
