### ISSUE TITLE
[ENH] Restore only deltas

### ISSUE THREAD

**Issue by amosstorkey** [rdiff-backup/rdiff-backup#604]
## Is your feature request related to a problem? Please describe.

Restoring all the information at a timepoint is often overkill - the user can trivially access the current files, as that is the point of reverse differential backup. Instead we often want to just restore just the deltas, which may be many order of magnitude smaller than the core data repository. Yet, at least as documented, AFAICS restore seems to assume we always want to restore everything.

## Describe the solution you'd like

I'd imagine a solution that enables me to provide properly accessible reverse differential backup to a user that doesn't require a restore request: i.e. a "yesterday" directory of the current back up and a "2 days" "4 days" "1 week" "1 month" "4 month" etc reverse differential versions containing only the files that are different from the yesterday directory. The current increments directory doesn't provide for that, in that it doesn't preserve user ownership, and isn't designed for user consumption. A simple option that restores only files that changed between two time points would provide that. Alternatively, an option that makes the "increments" directory designed for user consumption would work too.

## Describe alternatives you've considered

I guess there may be a way to dump a file changelog out and use that to restrict the restore request, but that is not obvious (to me) and does not appear to be documented.

## Additional context

It may be that is is already achievable, in which case this is just a documentation request. If someone points me in the right direction, such that I can succeed, I will then try to document it. It may also be that this would be better achieved via rsync (though I want the full revdiff bu too), or a combination of rdiff and rsync, in which case I have also missed a trick.

**Comment by ericzolf** [comment]
If you want _all_ the increments to be "human readable", rdiff-backup is probably the wrong tool, and that would only be possible storing not only the changes but the whole file modified (an approach which costs disk space). AFAIK, some backup tools do this by hard-linking the files which haven't changed and copying the modified ones.

If you want to know which files have changed since a certain time, there are the `--list-changed-since` (compare between the latest backup and the given time) or the different `--compare*` (comparaison between backup and current situation) options. This gives you a list of file which have changed, which you can use as input for the `--include-filelist` option, followed by an `--exclude *` option (to exclude the files not included).

If I backup into the `bak` directory, and want to restore into the `to` directory, something like this works (it might need some more tweaking for your needs:

```
rdiff-backup --list-changed-since 3B bak | \
    grep -v '^changed \.$' | \
    sed -n -e 's/^changed */to\//p' -e 's/^new */to\//p' | \
    rdiff-backup -v 5 -r 3B --include-filelist-stdin --exclude
```
1. the first line lists files modified since 3 backups
2. the 2nd line avoids to match on the whole backuped directory and include everything (**NOTE:** directories are an issue as they include everything in them if they've changed)
3. 3rd line cleans up the output to transform it into a pure filelist (the "new" line is probably unnecessary because _new_ files aren't (yet) in the 3rd backup)
4. and the 4th line restores the directory based on the list of changed files

So, conclusion is that an option to only list changed files and not directories would be helpful in this approach (or to optionally mark them differently, so that they can be filtered out, e.g. a slash at the end). I think that a new option `--include/exclude-file-type`, applicable also to listing, could be a nice feature, probably useful for other purposes.

BTW, everything I've used is documented in the man-page...

**Comment by ikus060** [comment]
@amosstorkey It's not clear what behaviour you are looking for. Here my attempt to clarify.
You have a backup with file A,B,C,D. Within the last 30 days, only file B changes.
When you restore your data with `rdiff-backup --restore-as-of 30B <backup> <local-path>`, you want it to only download changes for file B since other file A,C,D didn't change. 

Plz confirm if this is the behaviour you are looking for.

@ericzolf You might confirm this, but to my knowledge, the restore process apply increments during the restore process.

**Comment by ericzolf** [comment]
It depends how you exactly mean it: of course, the restore process re-creates "true" files, using the mirror + increments, but IMHO it doesn't apply any delta to an existing target directory, it just recreates/transfers all the files.

Taking your example, the files A, B, C, D, would be restored as true file in the local-path, but having any of the files already present wouldn't reduce the amount of data transferred (but I might have missed something, the code is still particularly obscure at this place). Let's say I would be very surprised if it would be the case... :shrug:

**Comment by amosstorkey** [comment]
Apologies if I was not clear. Simply I want to restore to a new directory A only files changed between backup done at time t1 and backup done at time t2. In particular, this is most useful when t2 is the time of last backup. So yes ikus060 - that is correct.

**Comment by amosstorkey** [comment]
The point is that in most cases I care about there is a huge datastore (data from the last 25 years) and a very small number of changes. Restoring everything is infeasible. But restoring just the changed things and enabling recovery from that is trivial.

**Comment by amosstorkey** [comment]
@ericzolf - Thank you. I misunderstood and didn't realise that -include -exclude combination would work on the restore too. The man page could perhaps be more explicit that all options apply on restore in the "Restore" section of the man pages, though I agree it is mainly my failure in interpretation. In summary, I agree that this would work if only changed files and not changed directories could be specified, and this was very helpful pointer. Thanks.

**Comment by ericzolf** [comment]
The new man page is a lot clearer on which options apply to which action: https://github.com/rdiff-backup/rdiff-backup/blob/master/docs/rdiff-backup.1.adoc#actions

**Comment by ericzolf** [comment]
I close the issue, based on the last exchanges. Reopen it if you think that something was left open.
