### ISSUE TITLE
Get rid of $version and replace with other mean to centralize versioning

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#66]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericzolf](https://github.com/ericzolf)**
_Sunday Apr 14, 2019 at 11:06 GMT_
_Originally opened as https://github.com/ericzolf/rdiff-backup/issues/8_

----

Sounds to me like an SVN-ism that can't work with Git.

**Comment by ericzolf** [comment]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ericzolf](https://github.com/ericzolf)**
_Friday May 17, 2019 at 11:23 GMT_

----

Have a look at https://packaging.python.org/guides/single-sourcing-package-version/ - would also need to template the man pages. An idea might be to use the changelog as source for version?!?

**Comment by ottok** [comment]
To me if feels a bit unclean to have a changelog inside the git repository. The git commit log itself is already kind of a changelog, and if a curated and edited version is needed, it better suits the release notes or news items published on the website or elsewhere.

**Comment by ikus060** [comment]
For python project, I always use_scm_version. It's simple and easy to use
and maintain.

**Comment by ericzolf** [comment]
@ikus060 thanks for the hint, fixed as suggested with setuptools_scm.

**Comment by ottok** [comment]
Related, seems that Travis-CI has Github release integration. That could be used to automatically make a Github release on each master branch commit that has been tagged: https://docs.travis-ci.com/user/deployment/releases/

**Comment by ottok** [comment]
I fully agree that is is a good idea to define the version in one single place in the sources, instead of multiple places like now.

However populating the value of `__version__` from somewhere outside of the source itself (git tags are in `.git/...` which is not the source itself and will not be included in a .tar.gz export of the sources) does not seem to me like a good design idea, and is likely to backfire later on when it is time to automate releases on PyPi, .deb, .rpm etc.

I understand that the idea might seem witty at first and a cool thing to do. However in this case doing the boring thing and having a version number in the sources itself is what most other projects are doing and would be a tried-and-tested procedure. Using a novel approach here is likely to require much more work down the road engineering around all corner cases.

If @ikus060 thinks the current technical proposal in #87 is the way to go, maybe he can invest time in it and review and merge it?

This are a couple of examples of how other projects do releases/version:
- https://gitlab.com/pycqa/flake8/commit/aa792d2930b8f6dada3f6305e8a3704d2d191005
- https://github.com/ytdl-org/youtube-dl/commit/f620d0d860c34cd34e421247ed637a9d03f730ba#diff-48a98911b429d894888afa32ca5a7982
- https://github.com/pallets/flask/commit/ffc68840f821fb0a4c41a7b2b4eaad6d71f539b7

**Comment by ericzolf** [comment]
A '.tar.gz export of the sources` ought to be done via `./setup.py sdist` which would package the necessary version information. The only case where we might have issues would be using something like `git archive ...`. Balanced with all the advantages, the approach wins IMHO.

**Comment by ikus060** [comment]
Sorry to reopen this discussion, but working on travis/appveryor build I was surprised to see the version is hardcoded in `Version.py`.

Didn't we agreed to manage the version using scm_version ? The current way of managing the version cannot work in CICD world (Continious integration continuous delivery). In the continuous delivery, each pipeline and branches must have a unique numbering that is easy to track back to a git commit. Intermediate build between releases must also have a unique version too. scm_version does it all for us. I highly recommend to make use of `scm_version`.

Meanwhile #58 is blocked cause we can't push multiple version on pypi.

**Comment by ericzolf** [comment]
The issue was that the Git structures are being touched by scm_version, and I'm not happy to allow this (it leads to Git become unusable after a run with root, e.g. to install stuff).

**Comment by ikus060** [comment]
> The issue was that the Git structures are being touched by scm_version
It's because we used `write_to`. That changes the file.
Is that the only reason ? If yes, I can probably figure something out support scm_version and the Version.py

**Comment by ikus060** [comment]
Take a look at #152

**Comment by ikus060** [comment]
With the change to scm_version and the template feature added to setup.py, I think this task can be closed too.

**Comment by ericzolf** [comment]
Definitely. Next time, just add "Closes #66" in one of the commit comments, and it'll happen automatically once the PR is merged (magic!). I close it now manually.
