### ISSUE TITLE
[QUESTION] Incremental backup taking hours

### ISSUE THREAD

**Issue by wimg** [rdiff-backup/rdiff-backup#660]
## Bug summary

We use rdiff-backup to make a backup of VM snapshots. The number of files is quite limited (roughly 2000). The total size of the files is roughly 100GByte.
We backup from a remote SSH location. Connection speed (test with iperf) between the 2 hosts is 300-400Mbit/sec. Load on the systems is nearly non-existant.

Running rdiff-backup like this takes hours, with minimal network traffic (a few packets every 30 seconds or so) and no CPU usage except for a very occassional spike on the receiving end.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
2022-01-07 18:40:54.760353 +0100  <CLIENT-10870>  Using rdiff-backup version 2.0.5
2022-01-07 18:40:54.760520 +0100  <CLIENT-10870>        with cpython /usr/bin/python3 version 3.6.8
2022-01-07 18:40:54.767759 +0100  <CLIENT-10870>        on Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core, fs encoding utf-8
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
/usr/local/bin/rdiff-backup --print-statistics -v5 --ssh-no-compression "backup@172.16.100.10::/volume1/backup/db01" "/backup/db01"
```

## What happened and what did you expect?

Expected behaviour would be a much faster backup, with either CPU, disk or network maxing out.
Instead there is no CPU load (except for an occassional spike to 40%), a few packets every 30-60secs and no IO wait.

**Comment by ericzolf** [comment]
What happens if you simply rsync the same files between the same two servers? Does it happen for the initial backup and/or for the incremental ones as well? You write that it takes "hours", how many of those hours? Could you please call rdiff-backup with -v9 (for the time stamps) so that we see where the time is going? Do you have the same version of CentOS and rdiff-backup on both sides?

If I didn't miscalculate: 100 GBytes * 1024 * 8 bits / 300MB/s = 2730 sec = 45min...

**Comment by ericzolf** [comment]
No answer, closing.
