### ISSUE TITLE
[ENH] when removing increments, optionally show the size of each removed increment

### ISSUE THREAD

**Issue by pcanning** [rdiff-backup/rdiff-backup#740]
## Is your feature request related to a problem? Please describe.

Tools like rdiff-backup make it very easy to create and manage backups.  The biggest problem I have is managing the storage for the backups.  I have a script that
1. displays the storage capacity and usage of the backup destination volume before the backup
2. removes increments before some time period (e.g. 1 year)
3. does the backup showing backup statistics (i.e. --print-statistics)
4. displays the storage capacity and usage of the backup destination volume after the backup
5. verifies the backup
6. lists the changes in the last backup (--list-changed-since 1B)
7. lists all the increments and their sizes

This provides me some information about how/why my backup storage usage changed each day, but there are two things that would be helpful.
1. when removing increments, optionally show the size of each removed increment
2. when listing changes since ..., optionally show the size of each new/deleted file and the change in size of each changed file

For me, item 2 would be nice-to-have, but item 1 is important.

## Describe the solution you'd like

In rdiff-backup 2.2 (syntax) added a --size option to the "remove increments" action that would display the sizes of each removed increment.

**Comment by ericzolf** [comment]
I've split the issue into two different ones, see also #768

**Comment by ericzolf** [comment]
Some comments on this enhancement request:

1. you should already have quite a lot of the code necessary as part of the "list increments" action, as it already has a `--size` option.
2. basically, using the function `self.repo.get_increments_sizes()` you should have already all the information you need and only need to output it accordingly.
3. important is that you don't create "holes" through the repository encapsulation. If you need information from the repository, create a function (consider that it might impact the API), but don't fiddle _in the action_ with the internas of the repository. This was done in the past, and this is what I'm currently trying to get rid of, so don't add to the mess, please!
4. else, if you have something somewhat running, feel free to create a draft PR and i can do an early review to make sure it goes in the right direction.

**Comment by pcanning** [comment]
I've added code to add a --size option to the "remove increments" command, and to experiment I've added code to `RemoveAction._get_removal_time` that calls `self.repo.get_increments_sizes()` if the --size option is specified.  When I invoke `rdiff-backup remove increments --older-than 1D --size ...` I get

> AssertionError: Root path 'None' must be a real remote path.

at

> File "/tmp/rdiff-backup-env/lib/python3.10/site-packages/rdiff_backup-2.1.3b4.dev12+gfb1bd92.d20221109-py3.10-linux-x86_64.egg/rdiff_backup/selection.py", line 93, in __init__
>     assert isinstance(rootrp, rpath.RPath), (
> 

It appears this is caused by `self.repo.ref_path` being `None`.  Looking at how the `Repo` is created and initialized in `ListAction`, it appears `ref_path` gets initialized (to non-None) when `can_be_sub_path=True` is passed when creating the `Repo`.  I suspect, however, that passing `can_be_sub_path=True` when creating the `Repo` in RemoveAction would be incorrect (I haven't tried it through).

Any advise on how to proceed?

**Comment by ericzolf** [comment]
It wouldn't be correct to set `can_be_sub_path=True` because you can't remove a partial increment, hence it would be incorrect indeed. Because the function(s) `get_increments...` were meant initially for the `list increments` actions, which can use a sub_path, that's why these functions are using `ref_path`.

I see two possible courses of action:

1. set ref_path to base_dir in the cases where can_be_sub_path is False (and accordingly ref_inc), it's a more generic approach, which can have impact on other parts of the code, also positively because other functions might become usable in a more generic context, like `get_increments_sizes`.
2. use something like `self.ref_path or self.base_dir` where you need a "real" path, it's more tactical and less intrusive, but doesn't make the code nicer, and might have shortcomings

After a quick look at the code, you not only need ref_path but also ref_inc, so that the 1st course of action seems more promising, if also more intrusive. But I guess, it was already clear that your changes would only be accepted in the 2.3/2.4 development phase, so I'm fine with the "intrusion".

**Comment by ericzolf** [comment]
I added this issue to the 2.4.0 milestone. Even if you struggle a bit with your PR, you'll have many months to complete it.
