### ISSUE TITLE
[BUG] Bad Index Order when Regressing Backup

### ISSUE THREAD

**Issue by Gamrix** [rdiff-backup/rdiff-backup#869]
## Bug Summary: 

I am getting the following error when running `rdiff-backup` on my machine.

## Version, Python, OS
I am running `rdiff-backup 2.2.4` on Windows 10, using the prepackaged `.exe` downloaded from the repo.

The source is an local disk with an NTFS filesystem.
The destination is a NAS that has a BTRFS filesystem, mounted as a network drive on my machine.

## rdiff-backup call
```
 E:\file_sync_utils\rdiff_backup\rdiff-backup.exe E:/ Z:/John_Backups/E_Drive_Backup --exclude-globbing-filelist E:/file_sync_utils/rdiff_backup/exclude_dirs_e.txt
 ```

## What happened and what did you expect? 

```
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
WARNING: ListError: 'E:/$RECYCLE.BIN/S-1-5-18' [WinError 5] Access is denied: b'E:/$RECYCLE.BIN/S-1-5-18'
NOTE: Symbolic links excluded by default on Windows
WARNING: Previous backup seems to have failed, regressing destination now
NOTE: Regressing to date/time Thu Apr 13 22:42:51 2023
...
Traceback (most recent call last):
  File "rdiffbackup\run.py", line 170, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 105, in main_run
  File "rdiffbackup\actions\backup.py", line 139, in run
  File "rdiffbackup\actions\__init__.py", line 547, in _operate_regress
  File "rdiff_backup\regress.py", line 292, in Regress
  File "rdiff_backup\rorpiter.py", line 138, in __call__
ValueError: Bad index order: (b'long_filename_data', b'2') should be lower than (b'Documents', b'Downloads Folder backup', b'Downloads July -Dec 2014', b'Study sheet.docx').
```
I expected no error to occur. 

Backup log from rerunning with -v9
[backup_log.zip](https://github.com/rdiff-backup/rdiff-backup/files/11362566/backup_log.zip)

Let me know if you need more information.

**Comment by ericzolf** [comment]
I'm starting to think that btrfs isn't a file system fit for backups, this is the 2nd time that we have a weird behaviour of similar kind, see #864 : the "Repeated index" error from this issue is of the same kind as your issue with "Bad index order", and few lines apart in the source code src/rdiff_backup/rorpiter.py:

```python
        if index == self.index:
            log.Log("Repeated index {ri}, bad filesystem?".format(ri=index),
                    log.WARNING)
        elif index < self.index:
            raise ValueError(
                "Bad index order: {sidx} should be lower than {idx}.".format(
                    sidx=self.index, idx=index))
```

I'm no btrfs-specialist but I'd try to do a `btrfsck` and see if it fixes the issue. I'm interested in the result because we might need to warn our users to avoid usage of btrfs for their backups.

**Comment by ericzolf** [comment]
And, @Gamrix, did btrfsck fix the issue?

**Comment by Gamrix** [comment]
I haven't been able to figure out how to run btrfsck on the Synology device (after I unmount the volume, btrfs check was unable to load the volume). However, I realized that Synology is using `encryptfs` on top of `btrfs`, which might mean that the issue is with `encryptfs` instead of `btrfs`. Also, it's not fun knowing that I am running quite old versions of both.

**Comment by ericzolf** [comment]
OK,

**Comment by Gamrix** [comment]
Sounds good

**Comment by acaso** [comment]
I think it is a rdiff-backup issue when regressing long named files.

Problem seems to be that `IterTreeReducer` (from `rorpiter.py`) expects to receive indexes in order, but for files that need to go into `long_filename_data` dir, it receives `long_filename_data`  as the path to the file (instead of the original path), which alphabetically may be out of order.

No wonder it may happen when the backup target is in an EncFS filesystem (and the source is not), as EncFS supports filenames up to 190 bytes while many other filesystems limit them to 255 bytes, but I guess it would happen in any other cases where files end up in `long_filename_data` dir.

It can be reproduced with [this shell script](https://github.com/rdiff-backup/rdiff-backup/files/11726584/reproduce_long_names_regress_error.txt) as a minimal example using an EncFS target.

**Comment by ericzolf** [comment]
Very well spotted @acaso , and thank you for the repeater, let's then re-open this issue and try to fix it.

**Comment by ericzolf** [comment]
I forgot to ask @acaso but do you want to fix the issue yourself? You seem to have gone already quite deep into the code, and I could use some help.

**Comment by acaso** [comment]
I intended to fix it myself, but being my first time diving into rdiff-backup's source code, I run out of free time so I left my feedback here instead. I will have more free time in a few weeks. I'll check then if the bug is still open and in that case will give it a try.

**Comment by ericzolf** [comment]
No sweat, I'm also time constrained. First one who starts tells the other :smile:

**Comment by ikus060** [comment]
FYI I started looking into this issue.

@acaso thanks alot for the repeater. This is indeed valuable. Clearly encfs is messing with something.
