### ISSUE TITLE
Remove directory from backup without rdiff-backup-delete present? 

### ISSUE THREAD

**Issue by benjamindaines** [rdiff-backup/rdiff-backup#903]
I'm running an older LTS release of Ubuntu (20.04.6), which packages rdiff-backup 2.0.0 and doesn't not seem to have rdiff-backup-delete at all (command not found).  I'm assuming this was added in a more recent release.  That being the case, what is the most recommended way to remove a directory that I failed to omit before the backup ran?  Obviously, I would like to do this in a way that doesn't break my backup, but I would very much like to reclaim 1.5TB of space on my backup drive.  

I do see a package in the repo called rdiff-backup-fs which is a fuse filesystem for mounting rdiff backups.  I have not played around with it, and don't know whether it will mount the back up as R/W.

Either way, what is the best way to reclaim this space?  Thanks.

**Comment by ericzolf** [comment]
You could simply try to download the rdiff-backup-delete from a newer version. To be clear, it's never been tested and it's at your own risk, but the repository format didn't change since then (at least not in a relevant way), so that I don't see why it shouldn't work. A copy of the backup before trying never hurts though, or a snapshot of the filesystem perhaps.

**Comment by ericzolf** [comment]
No reaction, closing. Re-open if you have more questions.
