### ISSUE TITLE
Attempt to backup arbitrary files and dirs

### ISSUE THREAD

**Issue by notklaatu** [rdiff-backup/rdiff-backup#919]
I want to *exclude* all files by default, and include only files listed in `--include-globbing-filelist`

But I want to retain the ability to exclude subdirectories arbitrarily.

Essentially, I only want to backup specific dirs in $HOME, not all. 
Some dirs also have subdirs that I want to exclude.

For example, I do want to backup `~/.local` but I do NOT want to backup `~/.local/share/Trash` or `~/.local/share/flatpak`

Maybe my logic is backwards. Is there a way to include and exclude files and dirs arbitrarily without getting an error that either my backup target isn't a directory, or that all dirs are included by default so my include statement is reduntant..?

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /home/klaatu/.local/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.9.10
system:
  fs_encoding: utf-8
  platform: Linux-5.15.38-x86_64-AMD_Ryzen_5_5600X_6-Core_Processor-with-glibc2.33
```

## rdiff-backup call

I'm using this:

```
$ rdiff-backup backup --print-statistics \
--exclude-globbing-filelist /home/klaatu/.excludes \
--include-globbing-filelist /home/klaatu/.includes  \
/home/klaatu/ \
/run/media/klaatu/mybackup/
```

Result:

```
Fatal Error: Last selection expression Command-line include glob: b'/home/klaatu/.zyn*'
only specifies that files be included. Because the default is to include all files, the expression is redundant.  Exiting because this
probably isn't what you meant
```

I tried this work-around:

```
$ rdiff-backup backup \
--include-if-present=.include \
--exclude-if-present=.exclude \
--include=src/.bashmc src/ dest/
```

And got the response:

```
Fatal Error: Last selection expression Command-line include glob: b'src/.bashmc'
only specifies that files be included.  Because the default is to
include all files, the expression is redundant.  Exiting because this
probably isn't what you meant
```

(which isn't true, because I placed `.exclude` in `src` so all files should be excluded in this case, and the `.include` files should override that.)

**Comment by ericzolf** [comment]
Rdiff-backup works after the first hit principle, so whatever matches first, include or exclude, is applied. Also, and this is your error message, there is an implicit include-all at the end, so whatever isn't matched explicitly, is included. See [those selection examples](https://rdiff-backup.net/examples.html#file_selection_with_includeexclude_options) for more information.

You should as well check the man page, it explains that patterns in an include / exclude file can be prefixed by `+ ` or `- ` to change its meaning so that you can mix includes and excludes in the same file. 

Please close the issue if you've got your answer.

**Comment by notklaatu** [comment]
Thank you, I appreciate the clear explanation. I'll make an attempt with the additional +/- notation.
