### ISSUE TITLE
[BUG] Removal of setup.py usage in debian/autobuild.sh regressed it

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#973]
## Bug summary

In commit cddb923 the title is to stop using setup.py. However, the commit message only lists the changes. There is no explanation of *why* the change was made as [typically git commit messages should](https://optimizedbyotto.com/post/good-git-commit/) have.

The file `setup.py` itself was however not removed. Thus just wondering, it the project going to use Python setuptools or not?

## What happened and what did you expect?

I came across this while trying to run:

```
± make dist_deb
podman run --rm -i -v /home/otto/koodia/rdiff-backup/rdiff-backup/..:/build/ -w /build/rdiff-backup rdiff-backup-dev:debian-sid debian/autobuild.sh
/usr/bin/env: 'python': No such file or directory
```

I reverted the change back to make it work again:

```diff
-VERSION="$(./tools/get_project_metadata.py Version)"
+VERSION="$(./setup.py --version)"
```

Seems project still uses setuptools and the setuptools API works just as expected.

**Comment by ottok** [comment]
Was this change related to `distutils` being deprecated in [Python 3.10+](https://peps.python.org/pep-0632)?

**Comment by ericzolf** [comment]
The setuptools have declared that the direct call of setup.py is deprecated, it should only be used as back-end for a front-end (according to many PEPs, 517, 518 and I think others). See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for a readable summary.

The deprecation of distutils, resp. the removal of it in 3.12, has other impacts, but not this one.

Another issue here is that no standard front-end, like `build`, does provide a direct way to grab the version, hence the need for a specific script (ugly, I know, but what shall I do?).

Anyway, as far as I can see, the fix is easy: use python3 instead of python.
